package projetException;

import java.util.Scanner;

public class Traitement {

	public static void main(String[] args) {
		testDiv();

	}

	static void testDiv() {
		Scanner sc = new Scanner(System.in);

		try {
			System.out.println("nb1");
			int nb1 = sc.nextInt();
			System.out.println("nb2");
			int nb2 = sc.nextInt();
			int res = Traitement.div(nb1, nb2);
			System.out.println(res);
		} catch (Exception e) {
			System.out.println("exception gérée");
		}
		System.out.println("fin du programme");

	}

}
